191 - githooks: Trigger: commit, Action: lint

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,19 +1,13 @@
-# #!/bin/sh
+#!/bin/sh
+# TODO - maybe install prettier (dev-dep). Solve lint/prettier.
+# Then run prettier before linting.
 
-# # Run linting
-# npm run lint
 
-# # Check if linting passed
-# if [ $? -ne 0 ]; then
-#   echo "Linting failed. Please fix the issues before committing."
-#   exit 1
-# fi
+# Run linting
+npm run lint
 
-# # Run build
-# npm run build
-
-# # Check if build passed
-# if [ $? -ne 0 ]; then
-#   echo "Build failed. Please fix the issues before committing."
-#   exit 1
-# fi
+# Check if linting passed
+if [ $? -ne 0 ]; then
+  echo "Linting failed. Please fix the issues before committing."
+  exit 1
+fi
